services:
  iobroker:
    restart: unless-stopped
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - "8081:8081"
    volumes:
      - ./iobrokerdata:/opt/iobroker

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "0"
    ports:
      - "3001:3000"
    volumes:
      - "./grafana_storage:/var/lib/grafana"
